plugin:
  # Suspends/Resumes a cronjob
  suspendCronsToggle:
    shortCut: Ctrl-P
    scopes:
      - cj
    description: susPend toggle
    command: kubectl
    background: true
    args:
      - patch
      - cronjobs
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
      - -p
      - '{"spec" : {"suspend" : $!COL3 }}'
