#!/bin/bash

# ITcat: Imgcat for plain-old Tmux.
# See https://gitlab.com/gnachman/iterm2/issues/3898

function print_osc() {
    printf "\033Ptmux;\033\033]"
}

function print_csi() {
    printf "\033["
}

function print_st() {
    printf "\a\033\\"
}

function print_image() {
    local fixed_height=20
    for i in `seq 1 $fixed_height`; do printf "\n"; done
    print_csi
    printf "?25l"
    print_csi
    printf "${fixed_height}F"
    print_osc
    printf '1337;File='
    if [[ -n "$1" ]]; then
      printf 'name='`echo -n "$1" | base64`";"
    fi
    if $(base64 --version 2>&1 | egrep 'fourmilab|GNU' > /dev/null)
    then
      BASE64ARG=-d
    else
      BASE64ARG=-D
    fi
    echo -n "$3" | base64 $BASE64ARG | wc -c | awk '{printf "size=%d",$1}'
    printf ";inline=$2"
    printf ";height=$fixed_height"
    printf ":"
    echo -n "$3"
    print_st
    printf '\n'
    if [[ -n "$4" ]]; then
      echo $1
    fi
    print_csi
    printf "${fixed_height}E"
    print_csi
    printf "?25h"
}

function error() {
    echo "ERROR: $*" 1>&2
}

function show_help() {
    echo "Usage: imgcat [-p] filename ..." 1>& 2
    echo "   or: cat filename | imgcat" 1>& 2
}

## Main

if [ -t 0 ]; then
    has_stdin=f
else
    has_stdin=t
fi

if [ $has_stdin = f -a $# -eq 0 ]; then
    show_help
    exit
fi

while [ $# -gt 0 ]; do
    case "$1" in
    -h|--h|--help)
        show_help
        exit
        ;;
    -p|--p|--print)
        print_filename=1
        ;;
    -*)
        error "Unknown option flag: $1"
        show_help
        exit 1
      ;;
    *)
        if [ -r "$1" ] ; then
            has_stdin=f
            print_image "$1" 1 "$(base64 < "$1")" "$print_filename"
        else
            error "imgcat: $1: No such file or directory"
            exit 2
        fi
        ;;
    esac
    shift
done

if [ $has_stdin = t ]; then
    print_image "" 1 "$(cat | base64)" ""
fi

exit 0
